Standups/Controllers/UserCommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Standups.Models.SUPModels;
using Standups.Models.Abstract;

namespace Standups.Controllers
{
    [Authorize]
    public class UserCommentsController : Abstract.BaseControllerWithIdentity
    {
        public UserCommentsController(ISUPRepository repo, ISUPCommentsRepository repo2) : base(repo, repo2)
        {
            
        }

        public ActionResult Rate(int? id)
        {
 /*           int idUse;
            if (id == null)
            {
                // Select the "first" one
                // newest
                idUse = commentsRepository.Questions
                        .Where(q => q.Active == 1)
                        .OrderByDescending(q => q.SubmissionDate)
                        .First()
                        .ID;
                // one with the most ratings?
                // with the best ratings?
            }
            else
            {
                idUse = id.Value;
            }
            ViewBag.QuestionID = idUse;
*/
            var questionsAvailable = commentsRepository.Questions.Where(q => q.Active == 1).ToList();

            return View(questionsAvailable);
        }

        public JsonResult Comments(int? id)
        {
            //System.Diagnostics.Debug.WriteLine($"Comments {id}");
            if(id == null)
            {
                return Json(new List<object>(), JsonRequestBehavior.AllowGet);
            }
            SUPQuestion q = commentsRepository.GetQuestionById(id.Value);
            if(q != null && q.Active == 1)
            {
                SUPUser user = GetCurrentSUPUser();

                var data = q.SUPComments.Where(c => c.AdvisorRating > 0).Select(c => new {
                    ID = c.ID,
                    TimeStamp = c.SubmissionDate,
                    UserRating = c.SUPCommentRatings.FirstOrDefault(cr => cr.SUPRaterUserID == (user?.ID ?? -1))?.RatingValue ?? 0,
                    Likes = c.SUPCommentRatings.Where(cr => cr.RatingValue > 0).Count(),
                    Dislikes = c.SUPCommentRatings.Where(cr => cr.RatingValue < 0).Count(),
                    Comment = c.Comment});
                return Json(data, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new List<object>(), JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult MakeRating()
        {
            string statusValue = "NOT OK";
            string cID = Request.Form["CommentID"];
            string act = Request.Form["Action"];
            int rating = 0;
            if(act == "UP")
            {
                rating = 1;
            }
            else if(act == "DOWN")
            {
                rating = -1;
            }

            int commentID;
            if(int.TryParse(cID, out commentID))
            {
                SUPUser user = GetCurrentSUPUser();
                if (user != null && commentsRepository.MakeCommentRating(user.ID, commentID, rating))
                {
                    statusValue = "OK";
                }
            }

            var data = new { status = statusValue };
            return Json(data);
        }

        // GET: UserComments/Create
        public ActionResult Create(int? questionID)
        {
            if (questionID == null)
            {
                return View("../Errors/Http404");
            }
            SUPQuestion q = commentsRepository.GetQuestionById(questionID.Value);
            if(q == null || q.Active < 1)
            {
                // Show them a page that says this question isn't open any more
                return RedirectToAction("QuestionUnavailable");
            }
            SUPComment sUPComment = new SUPComment
            {
                SUPQuestionID = questionID.Value,
                SUPQuestion = q
            };
            return View(sUPComment);
        }

        // POST: UserComments/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SUPQuestionID,Comment")] SUPComment sUPComment)
        {
            if (ModelState.IsValid)
            {
                sUPComment.SubmissionDate = DateTime.UtcNow;
                // new comments have an advisor rating of 0 to indicate they have not yet been reviewed for suitability to post
                sUPComment.AdvisorRating = 0;
                commentsRepository.InsertOrUpdateComment(sUPComment);
                commentsRepository.Save();
                return RedirectToAction("Thanks", new { questionID = sUPComment.SUPQuestionID });
            }

            return View(sUPComment);
        }

        public ActionResult QuestionUnavailable()
        {
            return View();
        }

        public ActionResult Thanks(int? questionID)
        {
            if (questionID == null)
            {
                return View("../Errors/Http404");
            }
            SUPQuestion q = commentsRepository.GetQuestionById(questionID.Value);
            if (q == null || q.Active < 1)
            {
                // Show them a page that says this question isn't open any more
                return RedirectToAction("QuestionUnavailable");
            }
            return View(q);
        }
    }
}

Standups/Views/Shared/QuestionsViewPartial.cshtml
@model IEnumerable<Standups.Models.SUPModels.SUPQuestion>

@{ 
    
}

<h2>Open Questions</h2>
<p>Please provide some feedback on the course.  Responses are <strong>anonymous and public</strong>.  
    Click a question to provide your response and then rate other responses.</p>
<ul class="list-group">
    @if (Model.Count() == 0)
    {
        <li class="list-group-item disabled">There are no questions at the moment.</li>
    }
    @foreach (var q in Model)
    {
        var linkText = $"{q.Question} <span class=\"badge\">{q.SUPComments.Count()}</span>";
        <li class="list-group-item"><strong>Q:</strong> 
            <a href="@Url.Action("Create","UserComments", new { questionID = q.ID })">
                @q.Question <span class="badge">@q.SUPComments.Where(c => c.AdvisorRating > 0).Count()</span>
            </a>
        </li>
    }
</ul>
<p>@Html.ActionLink("Review and Rate Comments", "Rate", "UserComments", null, htmlAttributes: new { @class = "btn btn-success" })</p>

Standups/Views/Shared/ReportDetailsPartial.cshtml
@model Standups.Models.SUPModels.SUPMeeting

@{
    ViewBag.Title = "SUPForm";
    string completedLabel = "What have you completed since the last meeting?";
    string planningLabel = "What are you planning to do now?";
    string obstaclesLabel = "What obstacles are preventing you from completing tasks?";
}

@*When the model has the ReadOnly flag set, we just display the contents in read-only text areas.  When false
  it's assumed we're in the create form and so also add the validation message.  Also, we don't need to display the 
  timestamp since it's auto generated.*@
    <div class="row">
        <div class="col-xs-12 col-md-4">
            <h2 class="">@Model.SUPUser.FullName</h2>
            @if (Model.ReadOnly)
            {
                <p class="text-muted">Posted: @Model.TimeStampInPacificTimeZone.ToString("MM/dd/yyyy @ H:mm")</p>
            }
        </div>
        <div class="col-xs-12 col-md-4 col-md-offset-2">
            <h3>@Model.SUPUser.SUPGroup.Name</h3>
            <p class="text-primary">"<em>@Model.SUPUser.SUPGroup.Motto</em>"</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">

            <div class="form-group">
                @Html.LabelFor(m => m.Completed, completedLabel, htmlAttributes: new { @class = "control-label" })
                @if (Model.ReadOnly)
                {
                    @Html.TextAreaFor(m => m.Completed, 5, 20, htmlAttributes: new { @class = "form-control", style = "min-width: 80%", @readonly = "readonly" });
                }
                else
                {
                    @Html.TextAreaFor(m => m.Completed, 5, 20, htmlAttributes: new { @class = "form-control", style = "min-width: 80%" });
                    @Html.ValidationMessageFor(m => m.Completed, null, new { @class = "text-danger field-validation" })
                }
               
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Planning, planningLabel, htmlAttributes: new { @class = "control-label" })
                @if(Model.ReadOnly)
                {
                    @Html.TextAreaFor(m => m.Planning, 5, 20, htmlAttributes: new { @class = "form-control", style = "min-width: 80%", @readonly = "readonly" });
                }
                else
                {
                    @Html.TextAreaFor(m => m.Planning, 5, 20, htmlAttributes: new { @class = "form-control", style = "min-width: 80%" });
                    @Html.ValidationMessageFor(m => m.Planning, null, new { @class = "text-danger" })
                }
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Obstacles, obstaclesLabel, htmlAttributes: new { @class = "control-label" })
                @if (Model.ReadOnly)
                {
                    @Html.TextAreaFor(m => m.Obstacles, 5, 20, htmlAttributes: new { @class = "form-control", style = "min-width: 80%", @readonly = "readonly" });
                }
                else
                {
                    @Html.TextAreaFor(m => m.Obstacles, 5, 20, htmlAttributes: new { @class = "form-control", style = "min-width: 80%" });
                    @Html.ValidationMessageFor(m => m.Obstacles, null, new { @class = "text-danger" })
                }
                
            </div>
        </div>
    </div>

Standups/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    @RenderSection("HeadContent", false)
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Standups", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.IsInRole("Admin"))
                    {
                        <!--li>@Html.ActionLink("Home", "Index", "Home")</li-->
                        <li>@Html.ActionLink("AdminHome", "Index", new { area = "Admin", controller = "Admin" }) </li>
                        <!--li>@Html.ActionLink("Grading", "Index", new { area = "Admin", controller = "Grading" })</li>
                        <li>@Html.ActionLink("Users", "Index", new { area = "Admin", controller = "Users" }) </li>
                        <li>@Html.ActionLink("Advisors", "Index", new { area = "Admin", controller = "Advisors" }) </li>
                        <li>@Html.ActionLink("Groups", "Index", new { area = "Admin", controller = "Groups" }) </li>
                        <li>@Html.ActionLink("Reports", "Index", new { area = "Admin", controller = "Reports" }) </li-->
                    }
                    else
                    {
                        <!--li>@Html.ActionLink("Home", "Index", "Home")</li-->
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <div class="row">
            <div class="col-md-8">
                <hr />
            </div>
        </div>
        <footer>
            <p>&copy; 2017 - CS 460/1/2 Software Engineering - Western Oregon University</p>
        </footer>
    </div>

    @* @Scripts.Render("~/bundles/jquery") *@
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>