Standups/Areas/Admin/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Standups.Models.SUPModels;
using Standups.Models.SUPViewModels;

namespace Standups.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ReportsController : Controller
    {
        private SUPContext db = new SUPContext();

        // GET: Admin/Reports
        public ActionResult Index()
        {
            var sUPMeetings = db.SUPMeetings.Include(s => s.SUPUser).OrderByDescending(m => m.SubmissionDate).ToList();

            MeetingsViewModel vm = new MeetingsViewModel
            {
                CurrentUser = null,
                Meetings = sUPMeetings
            };

            return View(vm);
        }

        // GET: Admin/Reports/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SUPMeeting sUPMeeting = db.SUPMeetings.Find(id);
            if (sUPMeeting == null)
            {
                return HttpNotFound();
            }
            return View(sUPMeeting);
        }

        // GET: Admin/Reports/Create
        public ActionResult Create()
        {
            ViewBag.SUPUserID = new SelectList(db.SUPUsers, "ID", "FirstName");
            return View();
        }

        // POST: Admin/Reports/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,SubmissionDate,SUPUserID,Completed,Planning,Obstacles")] SUPMeeting sUPMeeting)
        {
            if (ModelState.IsValid)
            {
                db.SUPMeetings.Add(sUPMeeting);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.SUPUserID = new SelectList(db.SUPUsers, "ID", "FirstName", sUPMeeting.SUPUserID);
            return View(sUPMeeting);
        }

        // GET: Admin/Reports/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SUPMeeting sUPMeeting = db.SUPMeetings.Find(id);
            if (sUPMeeting == null)
            {
                return HttpNotFound();
            }
            ViewBag.SUPUserID = new SelectList(db.SUPUsers, "ID", "FirstName", sUPMeeting.SUPUserID);
            return View(sUPMeeting);
        }

        // POST: Admin/Reports/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,SubmissionDate,SUPUserID,Completed,Planning,Obstacles")] SUPMeeting sUPMeeting)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sUPMeeting).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.SUPUserID = new SelectList(db.SUPUsers, "ID", "FirstName", sUPMeeting.SUPUserID);
            return View(sUPMeeting);
        }

        // GET: Admin/Reports/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SUPMeeting sUPMeeting = db.SUPMeetings.Find(id);
            if (sUPMeeting == null)
            {
                return HttpNotFound();
            }
            return View(sUPMeeting);
        }

        // POST: Admin/Reports/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SUPMeeting sUPMeeting = db.SUPMeetings.Find(id);
            db.SUPMeetings.Remove(sUPMeeting);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Standups/Areas/Admin/Views/Reports/Create.cshtml
@model Standups.Models.SUPModels.SUPMeeting

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SUPMeeting</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SubmissionDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SubmissionDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SubmissionDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SUPUserID, "SUPUserID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SUPUserID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SUPUserID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Completed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Completed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Completed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Planning, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Planning, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Planning, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Obstacles, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Obstacles, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Obstacles, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Standups/Areas/Admin/Views/Reports/Delete.cshtml
@model Standups.Models.SUPModels.SUPMeeting

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SUPMeeting</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SUPUser.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SUPUser.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SubmissionDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubmissionDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Completed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Completed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Planning)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Planning)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Obstacles)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Obstacles)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Standups/Areas/Admin/Views/Reports/Details.cshtml
@model Standups.Models.SUPModels.SUPMeeting

@{
    ViewBag.Title = "SUP Meeting Form";
    Model.ReadOnly = true;
}

<div class="page-header">
    <h1>Stand-Up Meetings <small>Report Form</small></h1>
</div>

<div class="container-fluid">
    @Html.Partial("ReportDetailsPartial", Model)
    <div>
        @Html.ActionLink("Back to All Reports", "Index")
    </div>
</div>

Standups/Areas/Admin/Views/Reports/Edit.cshtml
@model Standups.Models.SUPModels.SUPMeeting

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SUPMeeting</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.SubmissionDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SubmissionDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SubmissionDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SUPUserID, "SUPUserID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SUPUserID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SUPUserID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Completed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Completed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Completed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Planning, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Planning, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Planning, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Obstacles, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Obstacles, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Obstacles, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Standups/Areas/Admin/Views/Reports/Index.cshtml
@model Standups.Models.SUPViewModels.MeetingsViewModel

@{
    ViewBag.Title = "Index";
}

@section HeadContent
{
    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.15/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.js"></script>
}

@section scripts
{
    <script>
        $(document).ready(function ()
        {
            //console.log("running datatables...");
            $('#reports_table').DataTable();
        });
    </script>
}

<div class="container-fluid">
    <div class="page-header">
        <h1>Stand-Up Meetings <small>Past Reports</small></h1>
    </div>

    <div class="col-xs-12 col-md-12">
        <table class="table" id="reports_table">
            <thead>
                <tr>
                    <th></th>
                    <th>
                        @Html.DisplayNameFor(model => model.Meetings.FirstOrDefault().SUPUser.FullName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Meetings.FirstOrDefault().SubmissionDate)
                    </th>
                    <th>
                        Day
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Meetings.FirstOrDefault().Completed)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Meetings.FirstOrDefault().Planning)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Meetings.FirstOrDefault().Obstacles)
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Meetings)
                {
                        <tr>
                            <td style="width:80px;">
                                <div class="btn-group btn-group-xs" role="group" aria-label="Details and Delete" style="display: inline;">
                                    <a href="@Url.Action("Details", "Reports", new { id = item.ID })" class="btn btn-default">
                                        <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                                    </a>
                                    <a href="@Url.Action("Delete", "Reports", new { id = item.ID })" class="btn btn-default">
                                        <span class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span>
                                    </a>
                                </div>
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.SUPUser.FullName)
                            </td>
                            <td>
                                @item.TimeStampInPacificTimeZone.ToString("MM/dd/yyyy @ H:mm") @item.PSTorPDT
                            </td>
                            @if (item.TimeStampMeetsCriteria(Model.classtime, Model.classdays))
                            {
                                <td class="success">@item.DayOfWeekString</td>
                            }
                            else
                            {
                                <td class="info">@item.DayOfWeekString</td>
                            }
                            <td>
                                @Html.DisplayFor(modelItem => item.Completed)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Planning)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Obstacles)
                            </td>
                        </tr>
                    }
            </tbody>
        </table>
    </div>

</div>


@*
    <a href="@Url.Action("Details", "Reports", new { id = item.ID })" class="btn btn-sm">
                                    <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                                </a>
                                <a href="@Url.Action("Delete", "Reports", new { id = item.ID })" class="btn btn-sm">
                                    <span class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span>
                                </a>
*@