Standups/Models/SUPViewModels/MeetingsViewModel.cs
using Standups.Models.SUPModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Standups.Models.SUPViewModels
{
    public class MeetingsViewModel
    {
        public int classtime = 12;
        public DayOfWeek[] classdays = new DayOfWeek[] { DayOfWeek.Monday, DayOfWeek.Tuesday, DayOfWeek.Wednesday, DayOfWeek.Thursday };

        public IEnumerable<SUPMeeting> Meetings { get; set; }
        public SUPUser CurrentUser { get; set; }
        public int NumberOfReports
        {
            get
            {
                return Meetings.Count();
            }
        }
    }
}

Standups/Controllers/MeetingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Standups.Models.SUPModels;
using Microsoft.AspNet.Identity;
using Standups.Models.SUPViewModels;

namespace Standups.Controllers
{
    // Need to refactor this class to use the repository

    [Authorize]
    public class MeetingsController : Controller
    {
        private SUPContext db = new SUPContext();

        // GET: Meetings
        public ActionResult Index()
        {
            string id = User.Identity.GetUserId();
            SUPUser user = db.SUPUsers.FirstOrDefault(u => u.ASPNetIdentityID == id);
            var sUPMeetings = db.SUPMeetings.Where(m => m.SUPUser.ID == user.ID).OrderByDescending(m => m.SubmissionDate).ToList();

            MeetingsViewModel vm = new MeetingsViewModel
            {
                CurrentUser = user,
                Meetings = sUPMeetings
            };

            return View(vm);
        }

        // GET: Meetings/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                // this version works fine but depends on the exact path of the error view compared to this action method's view
                return View("../Errors/Http404");
                // this one sends a redirect (302), which may not be what is desired, i.e. if it's not found then it should
                // return a 404, not a 302 which directs to a "404" page that may just return a 200!
                //return RedirectToAction("Http404", "Errors");
                // this one doesn't return a view, just sets the response code in the reply
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            // Get all meetings for this user
            string iid = User.Identity.GetUserId();
            SUPUser user = db.SUPUsers.FirstOrDefault(u => u.ASPNetIdentityID == iid);
            var sUPMeetings = db.SUPMeetings.Where(m => m.SUPUser.ID == user.ID);
            // then look for the one with the given index
            SUPMeeting sUPMeeting = sUPMeetings.Where(m => m.ID == id).FirstOrDefault();
            if (sUPMeeting == null)
            {
                return View("../Errors/Http404");
                //return HttpNotFound();
            }
            return View(sUPMeeting);
        }

        // GET: Meetings/Create
        public ActionResult Create()
        {
            string id = User.Identity.GetUserId();
            SUPUser user = db.SUPUsers.FirstOrDefault(u => u.ASPNetIdentityID == id);
            SUPMeeting mtg = new SUPMeeting { SUPUser = user };
            return View(mtg);
        }

        // POST: Meetings/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Completed,Planning,Obstacles")] SUPMeeting sUPMeeting)
        {
            string id = User.Identity.GetUserId();
            SUPUser user = db.SUPUsers.FirstOrDefault(u => u.ASPNetIdentityID == id);
            sUPMeeting.SUPUser = user;
            sUPMeeting.SUPUserID = user.ID;

            if (ModelState.IsValid)
            {
                sUPMeeting.SubmissionDate = DateTime.UtcNow;
                db.SUPMeetings.Add(sUPMeeting);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(sUPMeeting);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Standups/Views/Meetings/Create.cshtml
@model Standups.Models.SUPModels.SUPMeeting

@{
    ViewBag.Title = "SUPForm";
    Model.ReadOnly = false;
}

<div class="page-header">
    <h1>Stand-Up Meetings <small>Report Form</small></h1>
</div>

<div class="container-fluid">
            @using (Html.BeginForm("Create", "Meetings", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.Partial("ReportDetailsPartial", Model)
                <button type="submit" class="btn btn-primary">Submit</button>
            }
    <div>
        @Html.ActionLink("Back to All Reports", "Index")
    </div>
</div>

Standups/Views/Meetings/Details.cshtml
@model Standups.Models.SUPModels.SUPMeeting

@{
    ViewBag.Title = "SUP Meeting Form";
    Model.ReadOnly = true;
}

<div class="page-header">
    <h1>Stand-Up Meetings <small>Report Form</small></h1>
</div>

<div class="container-fluid">
    @Html.Partial("ReportDetailsPartial", Model)
    <div>
        @Html.ActionLink("Back to All Reports", "Index")
    </div>
</div>

Standups/Views/Meetings/Index.cshtml
@model Standups.Models.SUPViewModels.MeetingsViewModel

@{
    ViewBag.Title = "Past Standup Meeting Reports";
}

@section HeadContent
{
    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.15/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.js"></script>
}

@section scripts
{
    <script>
        $(document).ready(function ()
        {
            //console.log("running datatables...");
            $('#reports_table').DataTable();
        });
    </script>
}

<div class="container-fluid">
    <div class="row">
        <div class="page-header">
            <h1>Stand-Up Meetings <small>Past Reports</small></h1>
        </div>
        <div class="col-xs-12 col-md-4">
            <h2 class="">@Model.CurrentUser.FullName</h2>
        </div>
        <div class="col-xs-12 col-md-8">
            @if (Model.NumberOfReports == 0)
            {
                <p>You don't have any standup meeting reports yet.</p>
            }
            else
            {
                <table class="table table-striped" id="reports_table">
                    <thead>
                        <tr>
                            <th></th>
                            <th>
                                @Html.DisplayNameFor(model => model.Meetings.FirstOrDefault().SubmissionDate)
                            </th>
                            <th>Day</th>
                            <th>
                                @Html.DisplayNameFor(model => model.Meetings.FirstOrDefault().Completed)
                            </th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Meetings)
                        {
                            <tr>
                                <td>
                                    @Html.ActionLink("Details", "Details", new { id = item.ID })
                                </td>
                                <td>
                                    @item.TimeStampInPacificTimeZone.ToString("MM/dd/yyyy @ H:mm") @item.PSTorPDT
                                </td>
                                @if (item.TimeStampMeetsCriteria(Model.classtime, Model.classdays))
                                {
                                    <td class="success">@item.DayOfWeekString</td>
                                }
                                else
                                {
                                    <td class="info">@item.DayOfWeekString</td>
                                }
                                <td>
                                    @Html.DisplayFor(modelItem => item.Completed)
                                </td>

                            </tr>
                        }
                    </tbody>
                </table>
            }
            <p>
                @Html.ActionLink("Create New Report", "Create")
            </p>
            </div> 
        </div>
</div>